// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PizzaAPI.Models
{
    public partial class Pedidos
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(20)]
        public string Mesa { get; set; }
        [Required]
        public string Sabores { get; set; }
        public string Obs { get; set; }
        public string status { get; set; }
    }
}